/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accueil: typeof import('./src/components/Accueil.vue')['default']
    Apropos: typeof import('./src/components/Apropos.vue')['default']
    AreaChart: typeof import('./src/components/AreaChart.vue')['default']
    Card: typeof import('primevue/card')['default']
    Changelog: typeof import('./src/components/Changelog.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Listbox: typeof import('primevue/listbox')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Masthead: typeof import('./src/components/Masthead.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    Results: typeof import('./src/components/Results.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Selection: typeof import('./src/components/Selection.vue')['default']
    Station_ref: typeof import('./src/components/Station_ref.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
}
