[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "public; max-age=60"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=2592000; includeSubDomains"
    Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"
    Accept-CH = "Downlink,RTT,Device-Memory,Save-Data,DPR,Width"

    # Multi-key header rules are expressed with multi-line strings
    # To permit external fonts, fontawesome and google, style-src, font-src and script-src (optional) are mandatory
    # default-src 'self'; connect-src 'self' https://www.google-analytics.com;
    Content-Security-Policy = '''
    	script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google-analytics.com https://www.googletagmanager.com; 
	    img-src 'self' blob: *.google-analytics.com *.googletagmanager.com;
      worker-src 'self';
      '''
    
[[headers]]
  # Override cache duration for assets with periods in the filename (i.e. static assets) : 8 days
  for = "/*.*"
    [headers.values]
    cache-control = "public; max-age=691200"
